name: CI for LOMAP ES1B2

on:
  pull_request:
    branches: 
      - master
      - develop
  push:
    branches: 
      - develop

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm --prefix webapp ci
    - run: npm --prefix webapp test --coverage --watchAll
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  e2e-tests:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm --prefix webapp install
    - run: npm --prefix webapp run build
    - run: npm --prefix webapp run test:e2e
  docker-push-webapp:
    name: Push webapp Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    #needs: [e2e-tests]
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        API_KEY_GOOGLE_MAPS: ${{ secrets.API_KEY_GOOGLE_MAPS }}
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        CLOUDINARY_PRESET: ${{ secrets.CLOUDINARY_PRESET }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_API_SECRET: ${{ secrets.CLOUDINARY_API_API_SECRET }}
      with:
          name: arquisoft/lomap_es1b2/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: webapp
          buildargs: API_KEY_GOOGLE_MAPS, CLOUDINARY_CLOUD_NAME, CLOUDINARY_PRESET, CLOUDINARY_API_KEY, CLOUDINARY_API_API_SECRET
  # deploy:
  #   name: Deploy over SSH
  #   runs-on: ubuntu-latest
  #   needs: [docker-push-restapi,docker-push-webapp]
  #   steps:
  #   - name: Deploy over SSH
  #     uses: fifsky/ssh-action@master
  #     with:
  #       host: ${{ secrets.DEPLOY_HOST }}
  #       user: ${{ secrets.DEPLOY_USER }}
  #       key: ${{ secrets.DEPLOY_KEY }}
  #       command: |
  #         wget https://raw.githubusercontent.com/arquisoft/lomap_0/master/docker-compose-deploy.yml -O docker-compose.yml
  #         docker-compose stop
  #         docker-compose rm -f
  #         docker-compose pull   
  #         docker-compose up -d
